### ISSUE TITLE
Some issues during deployment and testing.

### ISSUE THREAD

**Issue by AjiteshSaranathK** [ChagataiDuru/Python-OCPP1.6-Simulator#1]
Hey, 
Number 1: Your requirement.txt which pip is referred to download the required dependencies are wrong --> easy fix.
Number 2: Can you please help in letting me know how pack() works in Tkinter as I am new to it. If I want to change the for example the dropdown box values in Charging Station Serial Number how are we supposed to do it?
Thanks

**Comment by AjiteshSaranathK** [comment]
My bad, just saw the whole code are you corresponding a Adruino to a specific charger ID? Seems like that and does the other details auto fill once connected? Would be good if you address this issue alone. Thanks.

**Comment by ChagataiDuru** [comment]
> Hey,
> Number 1: Your requirement.txt which pip is referred to download the required dependencies are wrong --> easy fix.
> Number 2: Can you please help in letting me know how pack() works in Tkinter as I am new to it. If I want to change the for example the dropdown box values in Charging Station Serial Number how are we supposed to do it?
> Thanks

Thank you for addressing the first issue I was using Conda this is the why probably will fix it real quick

> My bad, just saw the whole code are you corresponding a Adruino to a specific charger ID? Seems like that and does the other details auto fill once connected? Would be good if you address this issue alone. Thanks.

Yeah as you said actually this simulator correspond with my csms framework:
https://github.com/ChagataiDuru/OCPP-Framework/ which check the charger's serial id on connection in the BootNotification's payload and if charge station registered in the framework's db return the rest of the necessary data
